/**
 * @module NavbarComponent
 * @description Module containing the navigation bar component.
 */

import React from 'react';
import NavbarLogoComponent from './logo/NavbarLogoComponent.tsx';

import HamburgerIconComponent from './hamburger-icon/HamburgerIconComponent.tsx';
import NavbarMenuComponent from './navmenu/NavbarMenuComponent.tsx';

/**
 * Component for rendering the navigation bar.
 *
 * This component represents the top navigation bar of the application. It consists
 * of the application logo and the navigation menu generated by the
 * `NavbarMenuComponent`. This component is responsible for structuring the
 * navigation bar layout.
 *
 * @component
 * @returns {JSX.Element} - The rendered navigation bar component.
 * @example
 * ```tsx
 * <NavbarComponent />
 * ```
 */
const NavbarComponent = (): JSX.Element => {
	return (
		<nav className='navbar__container'>
			<NavbarLogoComponent />
			<NavbarMenuComponent />
			<HamburgerIconComponent />
		</nav>
	);
};

export default NavbarComponent;
